//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPersonas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public int Edad { get; set; }
        public decimal Salario { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> SexoId { get; set; }
        public Nullable<int> EstadoCivilId { get; set; }
    
        public virtual EstadoCivil EstadoCivil { get; set; }
        public virtual Sexo Sexo { get; set; }
    }
}
